---
- name: "Create new VM from Clone"
  hosts: hyper
  gather_facts: no
  remote_user: root

  tasks:
    - name: "Clone VM Template"
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: "{{ pm_passwd }}"
        api_host: "srv01"
        clone: "Ubuntu-cloudinit-template"
        node: "srv01"
        vmid: 9991
        name: "{{ vm_name }}"
        newid: "{{ vm_id | int }}"
        storage: Ceph-pool
        
    - name: "Update IP Address"
      command: "qm set {{ vm_id | int }} --ipconfig0 \"ip={{ ip_address }}/16,gw=10.10.0.1\""

    - name: "Start host"
      command: "qm start {{ vm_id | int }}"

    - name: "Migrate VM"
      command: "qm migrate {{ vm_id | int }} {{ vm_node }} --online"

    - name: "Add new host" 
      add_host:
        name: '{{ ip_address }}'
        groups: vm

    - name: "Wait 30 seconds for host to boot"
      pause:
        seconds: 30

- hosts: vm
  remote_user: webadmin
  gather_facts: no
  become: true

  tasks:
    - name: Write the new host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ ip_address }} >> /home/webadmin/.ssh/known_hosts"

    - name: "Ping the VM to ensure access"
      ping:

    - name: Update apt repo and cache on VM
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install Qemu Guest Agent
      apt:
        name: qemu-guest-agent
        state: present

    - name: Enable and Start Qemu Guest Agent
      service:
        name: "qemu-guest-agent.service"
        enabled: true
        state: started

    - name: Upgrade all packages on VM
      apt: upgrade=dist force_apt_get=yes