---
- name: "Create new VM from Clone"
  hosts: hyper
  gather_facts: no
  remote_user: root

  tasks:
    - name: "Clone VM Template"
      command: "qm clone 9991 {{ vm_id }} --name {{ vm_name }} --full true --description {{ vm_name }}" # Change base VMID or make it a variable

    - name: "Update IP Address"
      command: "qm set {{ vm_id }} --ipconfig0 \"ip={{ ip_address }}/16,gw=10.10.0.1\"" # Change to match network configuration

    - name: "Update Memory"
      command: "qm set {{ vm_id }} --memory {{ memory }}"
      when: memory is defined

    - name: "Update Cloud Init"
      command: "qm cloudinit update {{ vm_id }} "

    - name: "Start host"
      command: "qm start {{ vm_id }}"

    - name: "Add VM to HA Manager"
      command: "ha-manager add {{ vm_id }} --state started"

    - name: "Migrate VM"
      command: "qm migrate {{ vm_id }} {{ vm_node }} --online"
      when: vm_node != "srv01"

    - name: "Add new host" 
      add_host:
        name: '{{ ip_address }}'
        groups: vm

    - name: "Wait 30 seconds for host to boot"
      pause:
        seconds: 30

###################################
#                                 #
#     INTIAL VM CONFIGURATION     #
#                                 #
###################################

- hosts: vm
  remote_user: webadmin
  gather_facts: no
  become: true

  tasks:
    - name: Write the new host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ ip_address }} >> /home/webadmin/.ssh/known_hosts"

    - name: "Ping the VM to ensure access"
      ping:

    - name: Update apt repo and cache on VM
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Install Qemu Guest Agent
      apt:
        name: qemu-guest-agent
        state: present

    - name: Enable and Start Qemu Guest Agent
      service:
        name: "qemu-guest-agent.service"
        enabled: true
        state: started

#####################################
#                                   #
#      ADDITIONAL CONFIGURATION     #
#                                   #
#####################################