# Step 1 Clone VM 
# Step 2 Set Cloud Init Data
# step 3 power on VM
# step 4 connect to new VM 
# step 5 Install initial configurations
---
- name: "Create new VM from Clone"
  hosts: hyper
  gather_facts: no

  tasks:
    - name: "Clone VM Template"
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: "{{ pm_passwd }}"
        api_host: "srv01"
        clone: "Ubuntu-cloudinit-template"
        node: "srv01"
        vmid: 9991
        name: "{{ vm_name }}"
        newid: "{{ vm_id | int }}"
        storage: Ceph-pool
        
    - name: "Update IP Address"
      command: "qm set {{ vm_id | int }} --ipconfig0 \"ip={{ ip_address }}/16,gw=10.10.0.1\""

    - name: "Migrate VM"
      command: "qm migrate {{ vm_id | int }} {{ vm_node }}"

    - name: "Start host"
      command: "qm start {{ vm_id | int }}"

    - name: "Add new host" 
      add_host:
        name: '{{ ip_address }}'
        groups: vm

- hosts: vm
  tasks:
    - name: "test ping"
      ping:
    





# - name: Write the new ec2 instance host key to known hosts
# connection: local
# shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"